from .user import User
# from .group import Group
from .apitoken import Apitoken
from .standard import Standard
from .subject import Subject
from .section import Section
from .academicyear import AcademicYear
from .academicyear_class import AcademicYearClass
from .academicyear_studenta import AcademicYearStudent
from .attendance import Attendance
from .leaverequest import LeaveRequest
from .exam import Exam
from .examallocation import ExamAllocation
from .subjectallocation import SubjectAllocation
from .questionpaper import QuestionPaper
from .mark import Mark
from .timetable import TimeTable
from .scholarship import Scholarship
from .studentscholarship import StudentScholarship
from .fees import Fees
from .feeshistory import FeesHistory
from .password_reset_otp import PasswordResetOTP