"""user table dummy column

Revision ID: 08f1fd70841d
Revises: 
Create Date: 2025-07-04 15:10:13.160690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08f1fd70841d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('Dateofbirth', sa.Date(), nullable=True),
    sa.Column('aadhaar_num', sa.String(length=70), nullable=True),
    sa.Column('Father_name', sa.String(length=50), nullable=True),
    sa.Column('Mother_name', sa.String(length=50), nullable=True),
    sa.Column('guardian_name', sa.String(length=50), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('pincode', sa.String(length=30), nullable=True),
    sa.Column('Father_pnum', sa.String(length=50), nullable=True),
    sa.Column('mother_pnum', sa.String(length=50), nullable=True),
    sa.Column('guardian_pnum', sa.String(length=50), nullable=True),
    sa.Column('blood_group', sa.String(length=30), nullable=True),
    sa.Column('religion', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=30), nullable=True),
    sa.Column('community', sa.String(length=30), nullable=True),
    sa.Column('is_hostel', sa.String(length=30), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('dummy', sa.String(length=20), nullable=True),
    sa.Column('user_type', mysql.TINYINT(), nullable=True, comment='1:Admin, 2:Principal, 3:Teacher, 4:Office_staff, 5:Driver, 6:Student'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apitoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apitoken')
    op.drop_table('user')
    # ### end Alembic commands ###
