"""all other tables

Revision ID: 15c5d8d9d231
Revises: b7d01f0856dc
Create Date: 2025-07-06 07:47:31.351578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '15c5d8d9d231'
down_revision = 'b7d01f0856dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.Column('school_fees', sa.Float(), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeshistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fees_id', sa.Integer(), nullable=True),
    sa.Column('paid_school_fees', sa.Float(), nullable=True),
    sa.Column('bal_school_fees', sa.Float(), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fees_id'], ['fees.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_scholarship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('acy_stud_id', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.String(length=30), nullable=True, comment='Paid or Pending'),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acy_stud_id'], ['academicyear_student.id'], ),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_allo_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sub_allo_id'], ['subject_allocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    op.drop_table('student_scholarship')
    op.drop_table('feeshistory')
    op.drop_table('fees')
    op.drop_table('scholarship')
    # ### end Alembic commands ###
