"""exam examallocation table

Revision ID: 3303be07caaf
Revises: cb8e22b7bd72
Create Date: 2025-07-05 23:06:02.884389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '3303be07caaf'
down_revision = 'cb8e22b7bd72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('ac_class_id', sa.Integer(), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ac_class_id'], ['academic_class.id'], ),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_allocation')
    op.drop_table('exam')
    # ### end Alembic commands ###
