"""subject  table

Revision ID: 33b4a4c45eba
Revises: 761337a8b062
Create Date: 2025-07-05 14:58:42.212394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b4a4c45eba'
down_revision = '761337a8b062'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
