"""standard table

Revision ID: 38f3d844b8ba
Revises: 4d8341a6bd2b
Create Date: 2025-07-04 17:46:49.053485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '38f3d844b8ba'
down_revision = '4d8341a6bd2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standards')
    # ### end Alembic commands ###
