"""all other tables

Revision ID: 394b23b26729
Revises: 15c5d8d9d231
Create Date: 2025-07-10 01:14:51.418446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394b23b26729'
down_revision = '15c5d8d9d231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
