"""user table dummy column

Revision ID: 4d8341a6bd2b
Revises: 08f1fd70841d
Create Date: 2025-07-04 17:43:22.220488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8341a6bd2b'
down_revision = '08f1fd70841d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
