"""section table

Revision ID: 54d8fbe8f56e
Revises: 13cc443628e1
Create Date: 2025-07-05 15:15:02.326068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d8fbe8f56e'
down_revision = '13cc443628e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
