"""all academic table creation

Revision ID: 5826b6958b15
Revises: e2a11c21ae16
Create Date: 2025-07-05 17:00:01.625851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5826b6958b15'
down_revision = 'e2a11c21ae16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
