"""standard table

Revision ID: 761337a8b062
Revises: 38f3d844b8ba
Create Date: 2025-07-05 14:55:27.657536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761337a8b062'
down_revision = '38f3d844b8ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
