"""sub-allo, qp, mark tables

Revision ID: b7d01f0856dc
Revises: 3303be07caaf
Create Date: 2025-07-06 07:14:12.900657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b7d01f0856dc'
down_revision = '3303be07caaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_allocation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ac_class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ac_class_id'], ['academic_class.id'], ),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acy_stud_id', sa.Integer(), nullable=True),
    sa.Column('exalloc', sa.Integer(), nullable=True),
    sa.Column('suballoc', sa.Integer(), nullable=True),
    sa.Column('obtained_mark', sa.Integer(), nullable=True),
    sa.Column('max_mark', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Pass or Fail'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acy_stud_id'], ['academicyear_student.id'], ),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['exalloc'], ['exam_allocation.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['suballoc'], ['subject_allocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionpaper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('exam_allo_id', sa.Integer(), nullable=True),
    sa.Column('sub_allo_id', sa.Integer(), nullable=True),
    sa.Column('qp_link', sa.String(length=100), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['exam_allo_id'], ['exam_allocation.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sub_allo_id'], ['subject_allocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionpaper')
    op.drop_table('mark')
    op.drop_table('subject_allocation')
    # ### end Alembic commands ###
