"""section table

Revision ID: e2a11c21ae16
Revises: 54d8fbe8f56e
Create Date: 2025-07-05 15:15:59.906520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'e2a11c21ae16'
down_revision = '54d8fbe8f56e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('status', mssql.TINYINT(), nullable=True, comment='1:Active,2:Inactive,-1:Deleted'),
    sa.Column('c_by', sa.Integer(), nullable=True, comment='Created by User ID'),
    sa.Column('c_at', sa.DateTime(), nullable=True),
    sa.Column('m_by', sa.Integer(), nullable=True, comment='Modified by User ID'),
    sa.Column('m_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['m_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section')
    # ### end Alembic commands ###
